# SPDX-FileCopyrightText: 2020-2025 PyPSA-SPICE Developers

# SPDX-License-Identifier: GPL-2.0-or-later

# coding: utf-8

power:
  p1: 
    name: Capacity by type
    units: GW
    graph_type: simple_bar_yearly_2
    tab_name: pow_cap_by_type_yearly
    leg_col: technology
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_cap_by_type'

  p2:
    name: Capacity by region
    units: GW
    graph_type: bar_with_filter
    tab_name: pow_cap_by_type_by_region_yearly
    leg_col: technology
    fil_col: region
    yaxis_scale:
      min: 0
      max: "max"
    slider_id: 'd_{}_cap_by_type_region'
    download_id: '{}_cap_by_type_region'
  
  p3:
    name: Generation by type
    units: TWh
    graph_type: simple_bar_yearly_2
    tab_name: pow_gen_by_type_yearly
    leg_col: technology
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_down_gen_by_type_yearly'
  
  p4:
    name: Share category
    units: "%"
    graph_type: area_share_yearly
    tab_name: pow_gen_by_category_share_yearly
    leg_col: technology
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: 100
    download_id: '{}_down_gen_by_chategory_yearly'

  # p5:
  #   name: Generation by regions
  #   units: TWh
  #   graph_type: simple_bar_yearly
  #   tab_name: pow_gen_by_region_yearly
  #   leg_col: region
  #   yaxis_scale: # only valid when the chart does not include filters or sliders
  #     min: 0
  #     max: max
  #   download_id: '{}_down_gen_by_region_yearly'

  p6:
    name: Transmission capacity between regions
    units: GW
    graph_type: bar_with_filter
    tab_name: pow_intercap_by_region_yearly
    leg_col: from
    fil_col: to
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    slider_id: 'd_{}_intercap_by_region'
    download_id: '{}_intercap_by_region'

  p7:
    name: Hourly generation
    units: MW
    graph_type: simple_bar_hourly
    tab_name: pow_gen_by_type_hourly
    leg_col: technology
    slider_id: 'Gen: ({}):'
    download_id: '{}_down_pow_gen_by_type_hourly'

  p8:
    name: Regional hourly generation
    units: MW
    graph_type: filtered_bar_hourly
    tab_name: pow_gen_by_type_region_hourly
    leg_col: type_and_flow
    fil_col: "region"
    slider_id: "NodalFlow: {}"
    download_id: '{}_down_gen_by_type_region_hourly'

  p9:
    name: Energy demand by carrier
    units: TWh
    graph_type: simple_bar_yearly
    tab_name: ene_dmd_by_carrier_yearly
    leg_col: carrier
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_ene_dmd_by_carrier_yearly'

  p10:
    name: Hourly demand
    units: MW
    graph_type: simple_bar_hourly
    tab_name: pow_elec_load_by_sector_hourly
    leg_col: sector
    slider_id: 'Load: ({}):".format(sce_name)'
    download_id: '{}_down_elec_load_by_sector_hourly'

  p11:
    name: Hourly elec price
    units: USD/MWh
    graph_type: simple_line_hourly
    tab_name: pow_marginal_price_by_region_hourly
    leg_col: region
    slider_id: 'Price: ({}):".format(sce_name)'
    download_id: '{}_down_marginal_price_by_region_hourly'
  
  p12:
    name: Nodal flow between regions
    units: MW
    graph_type: simple_line_hourly
    tab_name: pow_nodal_flow_hourly
    leg_col: flow
    download_id: '{}_nodal_flow_hourly'
    slider_id: 'NodalFlow_regions: {}'

  p13:
    name: Battery's E/P ratio
    graph_type: simple_bar_yearly
    tab_name: pow_bats_ep_ratio
    leg_col: bus
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_bats_ep_ratio'
  
  p14:
    name: Battery's charging profile
    units: MW
    graph_type: line_with_secondary_y_hourly
    tab_name: pow_bats_charging_hourly
    leg_col: status
    slider_id: 'battery_profile_{}'
    download_id: '{}_down_bats_charging_hourly'
    secondary_y_lab: ['stateOfCharge']
    primary_y_lab: ['powerFlow']

industry:
  i1: 
    name: Capacity by carrier
    units: GW
    graph_type: simple_bar_yearly
    tab_name: ind_cap_by_type_by_carrier_yearly
    leg_col: carrier
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_ind_cap_by_carier'

  i2:
    name: Capacity by region
    units: GW
    graph_type: bar_with_filter
    tab_name: ind_cap_by_carrier_by_region_yearly
    leg_col: carrier
    yaxis_scale:
      min: 0
      max: max
    fil_col: region
    slider_id: '{}_ind_cap_by_carrier_by_region'
    download_id: '{}_down_ind_cap_by_carrier_by_region'
  
  i3:
    name: Generation by region
    units: TWh
    graph_type: bar_with_filter
    tab_name: ind_gen_by_carrier_by_region_yearly
    leg_col: carrier
    yaxis_scale:
      min: 0
      max: max
    fil_col: region
    slider_id: '{}_gen_by_carrier_by_region_yearly'
    download_id: '{}_down_gen_by_carrier_by_region_yearly'

  i4:
    name: Generation by type
    units: TWh
    graph_type: simple_bar_yearly
    tab_name: ind_gen_by_type_by_carrier_by_heatgroup_yearly
    leg_col: technology
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_down_gen_by_type_by_carrier_by_heatgroup_yearly'

transport:
  t1: 
    name: EV load profile
    units: MW
    graph_type: line_with_secondary_y_hourly
    tab_name: tran_load_charging_all_hourly
    leg_col: status
    slider_id: '{}_tran_ev_profile'
    download_id: '{}_tran_load_charging_all_hourly'
    primary_y_lab: ["load", "charging", "storeDischarge"]
    secondary_y_lab: ["stateOfCharge"]

# for emissions and costs specify in which sectors graph should be included
# 'all': for in all power
# 'i': when industry is included
# 't': when transport is included

emissions:
  e1:
    name: Emission (power sector)
    units: MtCO₂
    graph_type: simple_bar_yearly
    tab_name: pow_emi_by_carrier_yearly
    leg_col: carrier
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_down_pow_emi_by_carrier_yearly'
    incl_sector: 'all' 

  e2: 
    name: Emission (industry sector)
    units: MtCO₂
    graph_type: simple_bar_yearly
    tab_name: ind_emi_by_carrier_yearly
    leg_col: carrier
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_ind_emi_by_carrier_yearly'
    incl_sector: 'i' 

costs:
  c1: 
    name: CAPEX by type (power sector)
    units: mUSD
    graph_type: simple_bar_yearly
    tab_name: pow_capex_by_type_yearly
    leg_col: technology
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_pow_capex_by_type_yearly'
    incl_sector: 'all'
    
  c2: 
    name: Overnight investment by type (power sector)
    units: mUSD
    graph_type: simple_bar_yearly
    tab_name: pow_overnight_inv_by_type_yearly
    leg_col: technology
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_overnight_inv_by_type_yearly'
    incl_sector: 'all'
    
  c3: 
    name: CAPEX by type (industry sector)
    units: mUSD
    graph_type: simple_bar_yearly
    tab_name: ind_capex_by_type_by_carrier_yearly
    leg_col: technology
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}ind_capex_by_type_by_carrier_yearly'
    incl_sector: 'i'
    
  c4: 
    name: CAPEX by type (transport sector)
    units: mUSD
    graph_type: simple_bar_yearly
    tab_name: tran_capex_by_type_yearly
    leg_col: technology
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_tran_capex_by_type_yearly'
    incl_sector: 't'
    
  c5: 
    name: CAPEX by Type (all energy sectors)
    units: mUSD
    graph_type: simple_bar_yearly
    tab_name: ene_capex_by_type_by_carrier_yearly
    leg_col: technology
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_ene_capex_by_type_by_carrier_yearly'
    incl_sector: 'all'
    
  c6: 
    name: CAPEX and OPEX (all energy sectors)
    units: mUSD
    graph_type: simple_bar_yearly
    tab_name: ene_costs_opex_capex_yearly
    leg_col: finance
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_ene_costs_opex_capex_yearly'
    incl_sector: 'all'
    
  c7:
    name: Average fuel costs (all energy sectors)
    units: USD/MWh_th
    graph_type: simple_line_yearly
    tab_name: ene_avg_fuel_costs_fuel_yearly
    leg_col: carrier
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_ene_avg_fuel_costs_fuel_yearly'
    incl_sector: 'all'
