# SPDX-FileCopyrightText: PyPSA-SPICE Developers

# SPDX-License-Identifier: GPL-2.0-or-later

# coding: utf-8

energy:
  e1:
    name: Total Primary Energy Supply (TPES)
    units: TWh
    graph_type: simple_bar_yearly
    table_name: ene_total_primary_supply
    leg_col: source
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_tpes_summary_by_sector'  
    
  e2:
    name: Total Primary Energy Supply (TPES)
    units: TWh
    graph_type: simple_bar_yearly
    table_name: ene_total_primary_supply
    leg_col: carrier
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_tpes_summary_by_carrier'  

  e3:
    name: Total Primary Energy Supply (TPES) by source
    units: TWh
    graph_type: bar_with_filter
    table_name: ene_total_primary_supply
    leg_col: carrier
    fil_col: source
    yaxis_scale:
      min: 0
      max: "max"
    slider_id: 'd_{}_tpes_summary'
    download_id: '{}_tpes_summary'

  e4:
    name: Total Final Energy Consumption (TFEC)
    units: TWh
    graph_type: simple_bar_yearly
    table_name: ene_total_final_consumption
    leg_col: final_energy
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_tfec_summary_by_sector'  

  e5:
    name: Total Final Energy Consumption (TFEC)
    units: TWh
    graph_type: simple_bar_yearly
    table_name: ene_total_final_consumption
    leg_col: carrier
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_tfec_summary_by_carrier'  

  e6:
    name: Total Final Energy Consumption (TFEC) by sector
    units: TWh
    graph_type: bar_with_filter
    table_name: ene_total_final_consumption
    leg_col: carrier
    fil_col: final_energy
    yaxis_scale:
      min: 0
      max: "max"
    slider_id: 'd_{}_tfec_summary'
    download_id: '{}_tfec_summary'

  e7:
    name: Total Final Energy Consumption (TFEC) - Resulting
    units: TWh
    graph_type: simple_bar_yearly
    table_name: ene_dmd_by_carrier_yearly
    leg_col: carrier
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_ene_dmd_by_carrier_yearly'  

  e8: 
    name: Energy Independence
    units: TWh
    graph_type: simple_bar_yearly
    table_name: ene_pe_import_local_ei_yearly
    leg_col: type
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_ene_pe_import_local_ei_yearly'

  e9:
    name: Energy not served
    units: GWh
    graph_type: simple_bar_yearly
    table_name: ene_not_served_warning
    leg_col: bus
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_ene_not_served_warning'

  e9:
    name: Sankey Diagram
    graph_type: sankey_diagram
    table_name: ene_sankey_diagram
    leg_col: source
    download_id: '{}_ene_sankey_diagram'


power:
  p1: 
    name: Capacity by type
    units: GW
    graph_type: simple_bar_yearly
    table_name: pow_cap_by_type_yearly
    leg_col: technology
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_cap_by_type'

  p2:
    name: Capacity by region
    units: GW
    graph_type: bar_with_filter
    table_name: pow_cap_by_type_by_region_yearly
    leg_col: technology
    fil_col: region
    yaxis_scale:
      min: 0
      max: "max"
    slider_id: 'd_{}_cap_by_type_region'
    download_id: '{}_cap_by_type_region'
  
  p3:
    name: Generation by type
    units: TWh
    graph_type: simple_bar_yearly
    table_name: pow_gen_by_type_yearly
    leg_col: technology
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_down_gen_by_type_yearly'
  
  p4:
    name: Share category
    units: "%"
    graph_type: area_share_yearly
    table_name: pow_gen_by_category_share_yearly
    leg_col: technology
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: 100
    download_id: '{}_down_gen_by_chategory_yearly'

  p5:
    name: Generation by regions
    units: TWh
    graph_type: simple_bar_yearly
    table_name: pow_gen_by_region_yearly
    leg_col: region
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_down_gen_by_region_yearly'

  p6:
    name: Transmission capacity between regions
    units: GW
    graph_type: bar_with_filter
    table_name: pow_intercap_by_region_yearly
    leg_col: from
    fil_col: to
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    slider_id: 'd_{}_intercap_by_region'
    download_id: '{}_intercap_by_region'

  p7:
    name: Power Emission
    units: MtCO₂
    graph_type: simple_bar_yearly
    table_name: pow_emi_by_carrier_yearly
    leg_col: carrier
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_down_pow_emi_by_carrier_yearly'

  p8:
    name: Hourly generation
    units: MW
    graph_type: simple_bar_hourly
    table_name: pow_gen_by_type_hourly
    leg_col: technology
    slider_id: 'Gen: ({}):'
    download_id: '{}_down_pow_gen_by_type_hourly'

  # p9:
  #   name: Regional hourly generation
  #   units: MW
  #   graph_type: filtered_bar_hourly
  #   table_name: pow_gen_by_type_region_hourly
  #   leg_col: type_and_flow
  #   fil_col: "region"
  #   slider_id: "NodalFlow: {}"
  #   download_id: '{}_down_gen_by_type_region_hourly'

  p10:
    name: Energy demand by carrier
    units: TWh
    graph_type: simple_bar_yearly
    table_name: ene_dmd_by_carrier_yearly
    leg_col: carrier
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_ene_dmd_by_carrier_yearly'

  p11:
    name: Hourly demand
    units: MW
    graph_type: simple_bar_hourly
    table_name: pow_elec_load_by_sector_hourly
    leg_col: sector
    slider_id: 'Load: ({}):".format(sce_name)'
    download_id: '{}_down_elec_load_by_sector_hourly'

  p12:
    name: Hourly elec price
    units: USD/MWh
    graph_type: simple_line_hourly
    table_name: pow_marginal_price_by_region_hourly
    leg_col: region
    slider_id: 'Price: ({}):".format(sce_name)'
    download_id: '{}_down_marginal_price_by_region_hourly'
  
  p13:
    name: Nodal flow between regions
    units: MW
    graph_type: simple_line_hourly
    table_name: pow_nodal_flow_hourly
    leg_col: flow
    download_id: '{}_nodal_flow_hourly'
    slider_id: 'NodalFlow_regions: {}'

  # p14:
  #   name: Battery's E/P ratio
  #   graph_type: simple_bar_yearly
  #   table_name: pow_bats_ep_ratio
  #   leg_col: bus
  #   yaxis_scale: # only valid when the chart does not include filters or sliders
  #     min: 0
  #     max: max
  #   download_id: '{}_bats_ep_ratio'
  
  # p15:
  #   name: BATS Charging profile
  #   units: MW
  #   graph_type: line_with_secondary_y_hourly
  #   table_name: pow_bats_charging_hourly
  #   leg_col: status
  #   slider_id: 'battery_profile_{}'
  #   download_id: '{}_down_bats_charging_hourly'
  #   secondary_y_lab: ['stateOfCharge']
  #   primary_y_lab: ['powerFlow']

  p16: 
    name: Hourly power generation and reserves
    units: MW
    graph_type: filtered_bar_hourly
    table_name: pow_gen_reserve_by_type_hourly
    leg_col: type
    fil_col: technology
    slider_id: "NodalFlow: {}"
    download_id: '{}_down_pow_gen_reserve_by_type_hourly'

  p17:
    name: Hourly Power Reserve [MW]
    graph_type: simple_line_hourly
    table_name: pow_reserve_by_type_hourly
    leg_col: technology
    slider_id: 'pow_reserve_by_type_hourly_{}'
    download_id: '{}_pow_reserve_by_type_hourly'

  # p18:
  #   name: Hourly Power Energy and Reserve [MW]
  #   graph_type: simple_bar_hourly
  #   table_name: pow_gen_reserve_by_type_hourly
  #   leg_col: technology
  #   slider_id: 'pow_gen_reserve_by_type_hourly_{}'
  #   download_id: '{}_pow_gen_reserve_by_type_hourly'

  p9: #largest and hardest to load, put it at the end
    name: Regional hourly generation
    units: MW
    graph_type: filtered_bar_hourly
    table_name: pow_gen_by_type_region_hourly
    leg_col: type_and_flow
    fil_col: region
    slider_id: "NodalFlow: {}"
    download_id: '{}_down_gen_by_type_region_hourly'

industry:
  i1: 
    name: Capacity by carrier
    units: GW
    graph_type: simple_bar_yearly
    table_name: ind_cap_by_type_by_carrier_yearly
    leg_col: carrier
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_ind_cap_by_carrier'

  i2: 
    name: Capacity by carrier and heat type
    graph_type: bar_with_filter
    table_name: ind_cap_by_type_by_carrier_yearly
    leg_col: carrier
    fil_col: heat_type
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    slider_id: '{}_ind_cap_by_type'
    download_id: '{}_ind_cap_by_type'

  i3:
    name: Capacity by regions
    units: GW
    graph_type: bar_with_filter
    table_name: ind_cap_by_carrier_by_region_yearly
    leg_col: carrier
    yaxis_scale:
      min: 0
      max: max
    fil_col: region
    slider_id: '{}_ind_cap_by_carrier_by_region'
    download_id: '{}_down_ind_cap_by_carrier_by_region'
  
  i4:
    name: Emission by fuel
    units: MtCO₂
    graph_type: simple_bar_yearly
    table_name: ind_emi_by_carrier_yearly
    leg_col: carrier
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_down_gen_by_type_by_carrier_yearly'

  i5: 
    name: Heat Generation by carrier
    units: TWh
    graph_type: simple_bar_yearly
    table_name: ind_gen_by_type_by_carrier_by_heatgroup_yearly
    leg_col: carrier
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_ind_gen_by_carrier'

  i6:
    name: Heat Generation by carrier 
    units: TWh
    graph_type: bar_with_filter
    table_name: ind_gen_by_type_by_carrier_by_heatgroup_yearly
    leg_col: carrier
    fil_col: heat_type
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    slider_id: '{}_gen_by_type_by_carrier_yearly_heattype'
    download_id: '{}_down_gen_by_type_by_carrier_yearly_heattype'


  i7:
    name: Heat Generation by regions
    units: TWh
    graph_type: bar_with_filter
    table_name: ind_gen_by_carrier_by_region_yearly
    leg_col: carrier
    yaxis_scale:
      min: 0
      max: max
    fil_col: region
    slider_id: '{}_gen_by_carrier_by_region_yearly'
    download_id: '{}_down_gen_by_carrier_by_region_yearly'

  i4:
    name: Generation by type
    units: TWh
    graph_type: simple_bar_yearly
    table_name: ind_gen_by_type_by_carrier_by_heatgroup_yearly
    leg_col: technology
    fil_col: region
    slider_id: "{}_ind_gen_by_type_hourly"
    download_id: '{}_down_ind_gen_by_type_hourly'


transport:
  t1: 
    name: EV Load Profiles
    units: MW
    graph_type: line_with_secondary_y_hourly
    table_name: tran_load_charging_all_hourly
    leg_col: status
    slider_id: '{}_tran_ev_profile'
    download_id: '{}_tran_load_charging_all_hourly'
    primary_y_lab: ["load", "charging", "storeDischarge", "lslo"]
    secondary_y_lab: ["stateOfCharge"]

  # t2: 
  #   name: EV Load Profiles by type
  #   units: MW
  #   graph_type: filtered_line_with_secondary_y_hourly
  #   table_name: tran_load_charging_all_hourly_by_type
  #   leg_col: status
  #   slider_id: '{}_tran_ev_profile'
  #   download_id: '{}_tran_load_charging_all_hourly'
  #   primary_y_lab: ["load", "charging", "storeDischarge", "lslo"]
  #   secondary_y_lab: ["stateOfCharge"]

  # t3: 
  #   name: EV Load Profiles by region
  #   units: MW
  #   graph_type: filtered_line_with_secondary_y_hourly
  #   table_name: tran_load_charging_all_hourly_by_region
  #   leg_col: status
  #   slider_id: '{}_tran_ev_profile'
  #   download_id: '{}_tran_load_charging_all_hourly'
  #   primary_y_lab: ["load", "charging", "storeDischarge", "lslo"]
  #   secondary_y_lab: ["stateOfCharge"]

  t4:
    name: Charger Capacity by type [GW]
    graph_type: simple_bar_yearly
    table_name: tran_charger_capacity_by_type_yearly
    leg_col: type
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_down_tran_charger_capacity_by_type_yearly'

  t5:
    name: Charger Capacity by region [GW]
    graph_type: simple_bar_yearly
    table_name: tran_charger_capacity_by_region_yearly
    leg_col: region
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_down_tran_charger_capacity_by_region_yearly'

  t6:
    name: Storage Capacity by type [GWh]
    graph_type: simple_bar_yearly
    table_name: tran_storage_capacity_by_type_yearly
    leg_col: type
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_down_tran_storage_capacity_by_type_yearly'

  t7:
    name: Storage Capacity by region [GWh]
    graph_type: simple_bar_yearly
    table_name: tran_storage_capacity_by_region_yearly
    leg_col: region
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_down_tran_storage_capacity_by_region_yearly'

# for emissions and costs specify in which sectors graph should be included
# 'all': for in all power
# 'i': when industry is included
# 't': when transport is included

emissions:
  e1: 
    name: Power Emission by carrier [MtCO2]
    graph_type: simple_bar_yearly
    table_name: pow_emi_by_carrier_yearly
    leg_col: carrier
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}pow_emi_by_carrier_yearly'
    incl_sector: 'all' 

  e2: 
    name: Industry Emission by Carrier [MtCO2]
    graph_type: simple_bar_yearly
    table_name: ind_emi_by_carrier_yearly
    leg_col: carrier
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_ind_emi_by_carrier_yearly'
    incl_sector: 'i' 

  e3: 
    name: All Emission by carrier [MtCO2]
    graph_type: simple_bar_yearly
    table_name: all_emi_by_carrier_yearly
    leg_col: carrier
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}all_emi_by_carrier_yearly'
    incl_sector: 'all' 

  e4: 
    name: All Emission by type [MtCO2]
    graph_type: simple_bar_yearly
    table_name: all_emi_by_type_yearly
    leg_col: type
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}all_emi_by_type_yearly'
    incl_sector: 'all' 

costs:
  c1: 
    name: CAPEX by type (Power)
    units: mUSD
    graph_type: simple_bar_yearly
    table_name: pow_capex_by_type_yearly
    leg_col: technology
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_pow_capex_by_type_yearly'
    incl_sector: 'all'
    
  c2: 
    name: OPEX by type (Power)
    units: mUSD
    graph_type: simple_bar_yearly
    table_name: pow_opex_by_type_yearly
    leg_col: technology
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_pow_opex_by_type_yearly'
    incl_sector: 'all'
    
  c3: 
    name: Fixed OPEX by type (Power)
    units: mUSD
    graph_type: simple_bar_yearly
    table_name: pow_fom_by_type_yearly
    leg_col: technology
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_pow_fom_by_type_yearly'
    incl_sector: 'all'

  c4: 
    name: Overnight investment by type (Power)
    units: mUSD
    graph_type: simple_bar_yearly
    table_name: pow_overnight_inv_by_type_yearly
    leg_col: technology
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_overnight_inv_by_type_yearly'
    incl_sector: 'all'
    
  c5: 
    name: CAPEX by type (Industry)
    units: mUSD
    graph_type: simple_bar_yearly
    table_name: ind_capex_by_type_by_carrier_yearly
    leg_col: technology
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_ind_capex_by_type_by_carrier_yearly'
    incl_sector: 'i'

  c6: 
    name: OPEX by type (Industry)
    units: mUSD
    graph_type: simple_bar_yearly
    table_name: ind_opex_by_type_by_carrier_yearly
    leg_col: technology
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_ind_opex_by_type_by_carrier_yearly'
    incl_sector: 'i'

  c7: 
    name: Fixed OPEX by type (Industry)
    units: mUSD
    graph_type: simple_bar_yearly
    table_name: ind_fom_by_type_by_carrier_yearly
    leg_col: technology
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_ind_fom_by_type_by_carrier_yearly'
    incl_sector: 'i'


  c8: 
    name: CAPEX by type (Transport)
    units: mUSD
    graph_type: simple_bar_yearly
    table_name: tran_capex_by_type_yearly
    leg_col: technology
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_tran_capex_by_type_yearly'
    incl_sector: 't'
    
  c9: 
    name: CAPEX by Type (Energy)
    units: mUSD
    graph_type: simple_bar_yearly
    table_name: ene_capex_by_type_by_carrier_yearly
    leg_col: technology
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_ene_capex_by_type_by_carrier_yearly'
    incl_sector: 'all'
    
  c10: 
    name: 'OPEX by Type (Energy)'
    units: mUSD
    graph_type: simple_bar_yearly
    table_name: ene_opex_by_type_by_carrier_yearly
    leg_col: technology
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_ene_opex_by_type_by_carrier_yearly'
    incl_sector: 'all'

  c11:
    name: 'FOM (Energy)'
    units: mUSD
    graph_type: simple_bar_yearly
    table_name: ene_fom_by_type_by_carrier_yearly
    leg_col: technology
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_ene_fom_by_type_by_carrier_yearly'
    incl_sector: 'all'

  c12: 
    name: 'CAPEX and OPEX (Energy)'
    units: mUSD
    graph_type: simple_bar_yearly
    table_name: ene_costs_opex_capex_yearly
    leg_col: finance
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_ene_costs_opex_capex_yearly'
    incl_sector: 'all'
    
  c13: 
    name: Avg. fuel costs (Energy)
    units: USD/MWh_th
    graph_type: simple_line_yearly
    table_name: ene_avg_fuel_costs_fuel_yearly
    leg_col: carrier
    yaxis_scale: # only valid when the chart does not include filters or sliders
      min: 0
      max: max
    download_id: '{}_ene_avg_fuel_costs_fuel_yearly'
    incl_sector: 'all'





