default_stages: [pre-commit]
exclude: ^(data|pypsa-spice-vis)/

repos:
  # ================================= PRE-COMMIT HOOKS =================================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        exclude: '^(data|docs)/.*'
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: '^(data|docs)/.*'
      - id: fix-encoding-pragma
        exclude: '^(data|docs)/.*'
      - id: mixed-line-ending
        exclude: '^(data|docs)/.*'
      - id: no-commit-to-branch

  # ================================== UPGRADE SYNTAX ==================================
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  # ======================================= BLACK ======================================
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
      - id: black-jupyter

  # ======================================= ISORT ======================================
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)

  # ====================================== FLAKE8 ======================================
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          - "flake8-bugbear==24.12.12"
          - "flake8-builtins==2.5.0"
          - "flake8-comprehensions==3.14.0"
          - "flake8-docstrings==1.7.0"
          - "flake8-eradicate==1.5.0"
          - "flake8-pytest-style==1.7.2"
          - "flake8-bandit==4.1.1"

  # ==================== PYLINT ====================
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-d duplicate-code",
            "--disable=fixme,import-error,line-too-long, protected-access",
            "--fail-under=9.5",
            "--good-names=i,j,k,ex,Run,_,pk,x,y,df,e,p",
            "--min-public-methods=0",
            "--generated-members=snakemake.*",
          ]
