# SPDX-FileCopyrightText: PyPSA-SPICE Developers

# SPDX-License-Identifier: GPL-2.0-or-later

default_stages: [pre-commit]
exclude: ^(data|pypsa-spice-vis)/

repos:
  # ================================= PRE-COMMIT HOOKS =================================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        exclude: '^(data|docs)/.*'
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: '^(data|docs)/.*'
      - id: mixed-line-ending
        exclude: '^(data|docs)/.*'
      - id: no-commit-to-branch

  # ================================== UPGRADE SYNTAX ==================================
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  # ======================================= BLACK ======================================
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
      - id: black-jupyter

  # ======================================= ISORT ======================================
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort

  # ====================================== FLAKE8 ======================================
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          - "flake8-bugbear==24.12.12"
          - "flake8-builtins==2.5.0"
          - "flake8-comprehensions==3.14.0"
          - "flake8-docstrings==1.7.0"
          - "flake8-eradicate==1.5.0"
          - "flake8-pytest-style==1.7.2"
          - "flake8-bandit==4.1.1"

  # ====================================== PYLINT ======================================
  - repo: https://github.com/pycqa/pylint
    rev: v3.3.8
    hooks:
      - id: pylint
