# SPDX-FileCopyrightText: PyPSA-SPICE Developers

# SPDX-License-Identifier: GPL-2.0-or-later

blank_issues_enabled: false

contact_links:
  - name: ðŸ“š Documentation
    url: https://agoenergy.github.io/pypsa-spice/
    about: Please check the documentation before opening a new issue.
  - name: ðŸ’¬ Discussions
    url: https://github.com/agoenergy/pypsa-spice/discussions
    about: For general discussions please use the Discussions page.
  - name: ðŸ›  Contribution
    url: https://agoenergy.github.io/pypsa-spice/contributing/contributing/
    about: Read this guide before adding issues or opening pull requests.
